export const currencies = {
  USD: { symbol: "$", rate: 1, decimals: 2 },
  IDR: { symbol: "Rp", rate: 16000, decimals: 0 },
  EUR: { symbol: "€", rate: 0.94, decimals: 2 },
  GBP: { symbol: "£", rate: 0.78, decimals: 2 },
  PHP: { symbol: "₱", rate: 56, decimals: 2 },
  CNY: { symbol: "¥", rate: 7.2, decimals: 2 },
  JPY: { symbol: "¥", rate: 150, decimals: 0 },
  CAD: { symbol: "C$", rate: 1.36, decimals: 2 },
  AUD: { symbol: "A$", rate: 1.52, decimals: 2 },
  SGD: { symbol: "S$", rate: 1.35, decimals: 2 },
  INR: { symbol: "₹", rate: 83, decimals: 1 },
  KRW: { symbol: "₩", rate: 1350, decimals: 0 },
  MYR: { symbol: "RM", rate: 4.7, decimals: 2 },
}

export const translations = {

  en: {
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    gathered: "Income",
    scattered: "Expense",
    total_treasure: "Our Savings",
    how_far: "How long we're set",
    months: "months",
    ask_honey_pot: "Should we get this?",
    set_limit: "Set our monthly cap...",
    spent: "spent together",
    save_changes: "Save",
    new_tale: "New Note",
    description: "For what?",
    amount: "How much?",
    category: "Category",
    tales: "Our logs",
    whispers: "Notes for us",
    food: "Food",
    transport: "Transport",
    housing: "Housing",
    shopping: "Shopping",
    bills: "Bills",
    days_left_title: "Days left this month",
    days: "days",
    daily_allowance: "For today",
    comfy_allowance: "We have plenty today!",
    comfy_allowance_sub: "Don't worry, we are doing beautifully well.",
    mod_allowance: "Let's be mindful today",
    mod_allowance_sub: "We're completely fine, just taking it easy.",
    tight_allowance: "Let's save a bit together",
    tight_allowance_sub: "We have what we need, just keeping it quiet.",
    empty_allowance: "All resting for now",
    empty_allowance_sub: "Ready for that reset together soon.",
    decide_bad: "Let's hold off on this one.",
    decide_warn: "Provisions are thinning, tread carefully.",
    decide_safe: "We're good to go ahead!",
    safe_notes_all_good: "We are wonderfully safe with where we're at.",
    safe_budget: "Everything is perfectly safe and sound.",
    bad_notes_overspent: "We spent a little over, let's keep an eye together.",
    warn_notes_adventures: "A few extra logs recently — just giving a nice thought.",
    budget_overspent: "A little past limit, we'll balance it together.",
    budget_almost: "Close to limit — we'll flow nicer tomorrow.",
    budget_warning: "Keep it simple today to take a safe breather.",
    opening_ledger: "Opening our little book..."
  },


  id: {
    greeting_morning: "Selamat pagi",
    greeting_afternoon: "Selamat sore",
    greeting_evening: "Selamat malam",
    gathered: "Masuk",
    scattered: "Keluar",
    total_treasure: "Tabungan kita",
    how_far: "Bisa bertahan",
    months: "bulan",
    ask_honey_pot: "Beli ini nggak ya?",
    set_limit: "Atur batas jajan...",
    spent: "dipakai jajan",
    save_changes: "Simpan",
    new_tale: "Catatan Baru",
    description: "Buat apa?",
    amount: "Berapa harganya?",
    category: "Kategori",
    tales: "Catatan kita",
    whispers: "Catatan buat kita",
    food: "Makanan",
    transport: "Transportasi",
    housing: "Rumah",
    shopping: "Belanja",
    bills: "Tagihan",
    days_left_title: "Sisa hari bulan ini",
    days: "hari",
    daily_allowance: "Jajan hari ini",
    comfy_allowance: "Bisa jajan banyak hari ini!",
    comfy_allowance_sub: "Tenang aja, tabungan kita masih aman banget.",
    mod_allowance: "Jajan dikit-dikit aja ya",
    mod_allowance_sub: "Kita masih aman, santai dulu aja jajan malam ini.",
    tight_allowance: "Kita hemat bareng ya",
    tight_allowance_sub: "Secukupnya aja ya, biar akhir bulan tetep aman.",
    empty_allowance: "Istirahat jajan dulu",
    empty_allowance_sub: "Siap-siap reset jajan bareng lagi.",
    decide_bad: "Tunda jajan yang ini dulu ya.",
    decide_warn: "Mulai menipis, hati-hati ya.",
    decide_safe: "Boleh banget, ambil aja!",
    safe_notes_all_good: "Tabungan kita masih aman dan terkendali.",
    safe_budget: "Semua aman dan tenang.",
    bad_notes_overspent: "Kita jajan lebih dikit, jaga bareng ya.",
    warn_notes_adventures: "Banyak catatan baru, cuma info aja ya.",
    budget_overspent: "Udah lewat batas limit, kita atur lagi bareng.",
    budget_almost: "Hampir lewat batas — flow jajan besok aja ya.",
    budget_warning: "Santai jajan hari ini, biar tenang tidurnya.",
    opening_ledger: "Buka buku catatan kita..."
  }

}
