export const currencies = {
  USD: { symbol: "$", rate: 1, decimals: 2 },
  IDR: { symbol: "Rp", rate: 16000, decimals: 0 },
  EUR: { symbol: "€", rate: 0.94, decimals: 2 },
  GBP: { symbol: "£", rate: 0.78, decimals: 2 },
  PHP: { symbol: "₱", rate: 56, decimals: 2 },
  CNY: { symbol: "¥", rate: 7.2, decimals: 2 },
  JPY: { symbol: "¥", rate: 150, decimals: 0 },
}

export const translations = {
  en: {
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    gathered: "Income",
    scattered: "Expenses",
    total_treasure: "Total Balance",
    how_far: "Runway Estimate",
    months: "months",
    ask_honey_pot: "Decide spending…",
    set_limit: "Monthly Budget Limit…",
    spent: "Spent",
    save_changes: "Save",
    new_tale: "New Entry",
    description: "Description",
    amount: "Amount",
    category: "Category",
    tales: "History",
    whispers: "Alerts & Guide",
    food: "Food",
    transport: "Transport",
    housing: "Housing",
    shopping: "Shopping",
    bills: "Bills",
    days_left_title: "Days Left in Month",
    days: "days",
    daily_allowance: "Daily Allowance",
    comfy_allowance: "Comfortable Daily Budget",
    comfy_allowance_sub: "Don't worry, you have a comfortable buffer for the rest of the month!",
    mod_allowance: "Moderate Daily Budget",
    mod_allowance_sub: "You're doing great! Just a little mindful spending and we're perfect.",
    tight_allowance: "Tight Daily Budget",
    tight_allowance_sub: "Funds are low, let's look out for each other and save together.",
    empty_allowance: "The pot is empty",
    empty_allowance_sub: "No remaining funds for the month.",
    decide_bad: "The honey pot says hold off on this one.",
    decide_warn: "Provisions are thinning, tread carefully.",
    decide_safe: "You may proceed with this expense.",
    safe_notes_all_good: "The honey pots are full and everything is wonderfully safe with us.",
    safe_budget: "Everything is perfectly safe and sound.",
    bad_notes_overspent: "We've spent a little more than we gathered, let's keep an eye out together.",
    warn_notes_adventures: "Memories are taking up a bit of our pot — just making sure you are mindful.",
    budget_overspent: "We've overspent a bit, but we'll balance it out together.",
    budget_almost: "Almost at our limit — let's slow down a bit for now.",
    budget_warning: "Treasury is thinning a little, let's take a safe breather."
  },
  id: {
    greeting_morning: "Selamat pagi",
    greeting_afternoon: "Selamat sore",
    greeting_evening: "Selamat malam",
    gathered: "Pemasukan",
    scattered: "Pengeluaran",
    total_treasure: "Total Saldo",
    how_far: "Estimasi Ketahanan",
    months: "bulan",
    ask_honey_pot: "Cek Pengeluaran…",
    set_limit: "Batas Anggaran Bulanan…",
    spent: "Terpakai",
    save_changes: "Simpan",
    new_tale: "Catatan Baru",
    description: "Deskripsi",
    amount: "Jumlah",
    category: "Kategori",
    tales: "Riwayat",
    whispers: "Panduan & Catatan",
    food: "Makanan",
    transport: "Transportasi",
    housing: "Tempat Tinggal",
    shopping: "Belanja",
    bills: "Tagihan",
    days_left_title: "Hari Tersisa di Bulan Ini",
    days: "hari",
    daily_allowance: "Uang Harian",
    comfy_allowance: "Anggaran Harian Aman",
    comfy_allowance_sub: "Tenang saja, kamu punya sisa batas aman yang cukup banyak!",
    mod_allowance: "Anggaran Harian Sedang",
    mod_allowance_sub: "Kamu hebat! Sedikit berhati-hati saja dan semuanya akan sempurna.",
    tight_allowance: "Anggaran Harian Tipis",
    tight_allowance_sub: "Dana menipis, mari kita berhemat bersama ya.",
    empty_allowance: "Madu telah habis",
    empty_allowance_sub: "Tidak ada dana tersisa untuk bulan ini.",
    decide_bad: "Madu bilang tunda dulu yang ini ya.",
    decide_warn: "Persediaan menipis, hati-hati ya.",
    decide_safe: "Kamu bisa lanjutkan pengeluaran ini.",
    safe_notes_all_good: "Pot madu penuh dan semua sangat aman bersama kita.",
    safe_budget: "Semuanya sangat aman dan terkendali.",
    bad_notes_overspent: "Kita belanja sedikit lebih banyak dari yang dikumpulkan, ayo saling menjaga.",
    warn_notes_adventures: "Kenangan menghabiskan sebagian dari tempat kita — menjaga agar Anda tetap hati-hati.",
    budget_overspent: "Kita belanja sedikit lebih banyak, tapi kita akan seimbangkan bersama.",
    budget_almost: "Hampir mencapai batas — ayo kurangi sedikit untuk saat ini.",
    budget_warning: "Keuangan menipis sedikit, mari bersantai sejenak."
  }
}
